language: python
python:
   - "2.7"
   - "2.6"
env:
   - DJANGO_VERSION=1.6 DJANGO_MIGRATOR='South>=1.0'
   - DJANGO_VERSION=1.7 DJANGO_MIGRATOR=''
# Django 1.7 doesn't support python 2.6, so explicitly exclude that
matrix:
   exclude:
      - python: "2.6"
        env: DJANGO_VERSION=1.7 DJANGO_MIGRATOR='South>=1.0'
# command to install dependencies,
install:
   # Install the right version of Django first
   - pip install 'Django<='"$DJANGO_VERSION" "$DJANGO_MIGRATOR"
   - pip install -r requirements.txt -r requirements-dev.txt --use-mirrors
# command to run tests
script: NOSE_WITH_COVERAGE=1 python manage.py test
